// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Locadora
{
    public partial class Categorias
    {
        public Categorias()
        {
            Filmes = new HashSet<Filmes>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Categoria { get; set; }

        [InverseProperty("IdcategoriaNavigation")]
        public virtual ICollection<Filmes> Filmes { get; set; }
    }
}