// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Locadora
{
    public partial class Filmes
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("IDCategoria")]
        public int? Idcategoria { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Sinopse { get; set; }

        [ForeignKey(nameof(Idcategoria))]
        [InverseProperty(nameof(Categorias.Filmes))]
        public virtual Categorias IdcategoriaNavigation { get; set; }
    }
}