// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Locadora
{
    [Index(nameof(LoginUsuario), Name = "UQ__Logins__3881FC40F6CDC0AB", IsUnique = true)]
    

    public partial class Logins
    {
        [Key]
        [Column("idUsuario")]
        public int IdUsuario { get; set; }
        [Column("loginUsuario")]
        [StringLength(15)]

        [Display(Name ="Login")]
        public string LoginUsuario { get; set; }
        [Display(Name = "Senha")]
        [Column("senhaUsuario")]
        [MaxLength(256)]
        public byte[] senhaUsuario { get; set; }
    }
}